### ISSUE TITLE
Go error trying to use this plugin on drone 0.8

### ISSUE THREAD

**Issue by olymk2** [drone-plugins/drone-pypi#14]
Is this known to still work i get this error

````
panic: EOF

goroutine 1 [running]:
github.com/drone/drone-go/plugin.MustParse()
	/drone/src/github.com/drone/drone-go/plugin/plugin.go:132 +0x59
main.main()
/drone/src/github.com/drone-plugins/drone-pypi/main.go:30 +0x24f
````

I have this config using the same url i use locally any ideas ?

````
  publish-pypi:
    image: plugins/drone-pypi
    repository: https://upload.pypi.org/legacy/
    username: ${pypi_username}
    password: ${pypi_password}
    distributions:
      - sdist
      - bdist_wheel
````
